### ISSUE TITLE
Formulario de registro-paso2

### ISSUE THREAD

**Issue by angela-goncalves** [frontendcafe/cmyk-orange#11]
![Q4N2s2rzQv](https://user-images.githubusercontent.com/66344422/131721017-f88e5ff6-f8fa-4076-bb52-221b1f3600ee.png)

**Comment by storres20** [comment]
Buenas noches
Me he asignado este issue y me he percatado que en el diseño del FIGMA se ha cambiado la imagen del lado derecho
¿Quisiera saber si voy a usar la imagen que se aprecia en este issue o la nueva imagen del FIGMA?

Tambien quiero pedirle porfavor pueda agrupar la imagen del circulo verde y el pequeño recuadro interno para poder descargarlo como un solo objeto. Similarmente para la nueva imagen del FIGMA.

Gracias

**Comment by storres20** [comment]
![image](https://user-images.githubusercontent.com/81504385/131808139-ab5b6f65-ed47-4b07-a23e-54a8d3050077.png)

**Comment by angela-goncalves** [comment]
Perdón que se cambio un poco el figma, pero ya esta listo ;) es la segunda imagen (la del figma) y ya agrupé el circulo con el idicativo de imagen ;)
